### ISSUE TITLE
kafka-stream@4.12.0 installation issue on window system

### ISSUE THREAD

**Issue by JsSbiz** [nodefluent/kafka-streams#122]
Hi Team,

I am new to Kafka-Stream, and i faced the following issue while installing it:

System Detail:
processor: Intel(R) Core(TM) i5-7500 CPU @ 3.40Ghz 3.41Ghz
RAM: 16.0 GB
System Type: 64 Bit Operating system, *64- based processor:

Issue Details:

PS E:\kstream> npm i kafka-streams@4.12.0 --save

> node-rdkafka@2.7.0 install E:\kstream\node_modules\node-rdkafka
> node-gyp rebuild

E:\kstream\node_modules\node-rdkafka>if not defined npm_config_node_gyp (node "C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
E:\kstream\node_modules\node-rdkafka\build\node-librdkafka.vcxproj(20,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Def
ault.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\jaswinder\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\kstream\node_modules\node-rdkafka
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN kstream@1.0.0 No description
npm WARN kstream@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rdkafka@2.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2019-07-12T05_25_46_835Z-debug.log

**Comment by alexbidule** [comment]
Same issue here. Did you manage to fix it ? Thanks
