### ISSUE TITLE
TypeError: createSubject is not a function  @ examples/window.js

### ISSUE THREAD

**Issue by raiscui** [nodefluent/kafka-streams#63]
`TypeError: createSubject is not a function
    at new Window (/root/kafkastream/node_modules/kafka-streams/lib/actions/Window.js:13:21)
    at KStream.window (/root/kafkastream/node_modules/kafka-streams/lib/dsl/KStream.js:286:24)
    at Object.<anonymous> (/root/kafkastream/window.js:65:41)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
`
in 'kafka-streams\lib\actions\Window.js'
`const {async: createSubject} = require("most-subject");`
I seeked most-subject there is no async method

**Comment by herbrandhofker** [comment]
I have same problem:) Stupid that we cannot use the windowing function. The rest is ok.
Maybe rewrite of windowing needed ?

**Comment by krystianity** [comment]
Hi there, thanks for reporting this issue. It should be fixed in kafka-streams@4.8.0

**Comment by gorillatron** [comment]
Im having this issue in version 4.9.0

**Comment by krystianity** [comment]
@gorillatron jup, typo -.- (will be)/ is gone, in 4.10.0
