### ISSUE TITLE
connectiing to multiple brokers

### ISSUE THREAD

**Issue by gilesbradshaw** [nodefluent/kafka-streams#92]
Hi I have 

    const kafkaStreams = new KafkaStreams(config)

with 

````
config = {
  noptions: {
    'metadata.broker.list': 'broker:9092, broker1:9093, broker2:9094',
    'group.id': 'api',
    'client.id': 'api',
    event_cb: true,
    'api.version.request': true,
    'compression.codec': 'snappy',

    'socket.keepalive.enable': true,
    'socket.blocking.max.ms': 100,

    'enable.auto.commit': true,
    'auto.commit.interval.ms': 1000,

    'heartbeat.interval.ms': 1000,
    'retry.backoff.ms': 250,

    'fetch.min.bytes': 100,
    'fetch.message.max.bytes': 2 * 1024 * 1024,
    'queued.min.messages': 100,

    'fetch.error.backoff.ms': 100,
    'queued.max.messages.kbytes': 50,

    'fetch.wait.max.ms': 1000,
    'queue.buffering.max.ms': 1000,

    'batch.num.messages': 10000,
  },
  tconf: {
    // 'auto.offset.reset': 'earliest',
    'request.required.acks': 1,
  },
}
````

however if any one of thoise brokers is down i get an error from 

````
stream.start(
        () => {
          console.log(`${topic} stream started, as kafka consumer is ready.`)
        }, (error) => {
          console.log(error.message, error.stack)
````

of 

rror: broker transport failure
    at NConsumer.stream.start.error (/Users/giles/Projects/msd-2-0/src/apps/api/build/index.js:1112:14)
    at NConsumer.emit (events.js:193:15)
    at KafkaConsumer.consumer.on.error (/Users/giles/Projects/msd-2-0/src/apps/api/node_modules/sinek/lib/librdkafka/NConsumer.js:364:15)
    at KafkaConsumer.emit (events.js:193:15)
    at eventHandler (/Users/giles/Projects/msd-2-0/src/apps/api/node_modules/node-rdkafka/lib/client.js:69:16)

should it not work ok if not all brokers are up?

thanks

**Comment by gilesbradshaw** [comment]
ah sorry closing - i get it - there's a different error when all brokers are down
